import { AirVent, BedDouble, Coffee, Droplets, Fan, Flame, HandPlatter, MapPin, Monitor, PackageCheck, Refrigerator, ScanFace, Shirt, ShowerHead, Snowflake, Sparkles, Tv, UsersRound, Utensils, Vault, Waves, Wifi } from "lucide-react";
import type { ComponentType } from "react";
import type { HabitacionAmenity, HabitacionesPageText, HabitacionRoomAmenityIcon } from "../interfaces";

export const IconosAmenidades: Record<HabitacionAmenity, ComponentType<{ size?: number }>
> = {
  capacity: UsersRound,
  bed: BedDouble,
  ac: Snowflake,
  tv: Tv,
  wifi: Wifi,
  ocean: Waves,
  bath: ShowerHead,
  coffee: Coffee,
  terrace: MapPin,
};

export const IconosAmenidadesHabitaciones: Record<HabitacionRoomAmenityIcon, ComponentType<{ size?: number }>> = {
  ac: AirVent,
  'smart-tv': Monitor,
  wifi: Wifi,
  safe: Vault,
  fan: Fan,
  'private-bath': ShowerHead,
  cleaning: Sparkles,
  towels: HandPlatter,
  'bath-kit': Droplets,
  terrace: Waves,
  minibar: Refrigerator,
  coffee: Coffee,
  iron: Shirt,
  'pool-towels': PackageCheck,
  'hair-dryer': AirVent,
  'makeup-mirror': ScanFace,
  stove: Flame,
  kitchenware: Utensils,
};

export const CAMPOS_FORM: Array<keyof HabitacionesPageText> = [
  'intro_body',
  'card_cta',
  'image_preview_label',
  'feature_heading',
  'room_amenities_title',
  'room_amenities_body',
  'request_amenities_title',
  'request_amenities_body',
  'policies_title',
  'policies_subtitle',
  'schedule_policy_title',
  'payment_policy_title',
  'cancellation_policy_title',
  'no_show_policy_title',
  'extra_guest_policy_title',
  'arrival_weeks_label',
  'refund_label',
  'credit_label',
  'check_in_label',
  'check_out_label',
  'reserve_cta',
  'call_cta',
  'bed_singular',
  'bed_plural',
  'guest_singular',
  'guest_plural',
  'guest_capacity_prefix',
];

export const TITULO_CAMPOS_FORM: any = {
  intro_title: "Título",
  intro_body: "Descripción",
  card_cta: "Pie de tarjeta",
  image_preview_label: "Título en imagen",
  feature_heading: "Título caracteristicas",
  room_amenities_title: "Título amenidades",
  room_amenities_body: "Descripción amenidades",
  request_amenities_title: "Título amenidades por solicitud",
  request_amenities_body: "Descripción amenidades por solicitud",
  policies_title: "Título de politicas",
  policies_subtitle: "Subtítulo de politicas",
  schedule_policy_title: "Título horario de politicas",
  payment_policy_title: "Título de política de pago",
  cancellation_policy_title: "Título de política de cancelación",
  no_show_policy_title: "Título de política (No show)",
  extra_guest_policy_title: "Título de persona extra",
  arrival_weeks_label: "Título de semanas de llegada",
  refund_label: "Título de reembolso",
  credit_label: "Título de crédito",
  check_in_label: "Título de check-in",
  check_out_label: "Título de check-out",
  reserve_cta: "Título de botón 'Reservar'",
  call_cta: "Título de botón 'Llamar'",
  bed_singular: "Título de cama (singular)",
  bed_plural: "Título de cama (plural)",
  guest_singular: "Título de huésped (singular)",
  guest_plural: "Título de huésped (plural)",
  guest_capacity_prefix: "Prefijo de huésped",
  name: "Nombre de habitación",
  short_description: "Descripción de habitación",
  capacity: "Capacidad",
  bed: "Nombre de cama",
};

export const AMENIDAD_TIPOS: Array<{value: HabitacionAmenity; label: string;}> = [
  { value: 'capacity', label: 'Capacidad' },
  { value: 'bed', label: 'Cama' },
  { value: 'ac', label: 'Aire acondicionado' },
  { value: 'tv', label: 'Televisión' },
  { value: 'wifi', label: 'Wi-Fi' },
  { value: 'ocean', label: 'Vista al mar' },
  { value: 'bath', label: 'Baño' },
  { value: 'coffee', label: 'Cafetera' },
  { value: 'terrace', label: 'Terraza' },
];

export const AMENIDAD_HABITACION_TIPOS: Array<{value: HabitacionRoomAmenityIcon; label: string;}> = [
  { value: 'ac', label: 'Aire acondicionado' },
  { value: 'smart-tv', label: 'Smart tv' },
  { value: 'wifi', label: 'Wifi' },
  { value: 'safe', label: 'Caja fuerte' },
  { value: 'fan', label: 'Ventilador' },
  { value: 'private-bath', label: 'Baño privado' },
  { value: 'cleaning', label: 'Limpieza' },
  { value: 'towels', label: 'Toallas' },
  { value: 'bath-kit', label: 'Kit de baño' },
  { value: 'terrace', label: 'Terraza' },
  { value: 'minibar', label: 'Minibar' },
  { value: 'coffee', label: 'Café' },
  { value: 'iron', label: 'Plancha' },
  { value: 'pool-towels', label: 'Toalla de baño' },
  { value: 'hair-dryer', label: 'Secadora de pelo' },
  { value: 'makeup-mirror', label: 'Espejo' },
  { value: 'stove', label: 'Estufa' },
  { value: 'kitchenware', label: 'Cocineta' },
];